stages:
  - build
  - test
  - publish
  - source

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive

Build:
  stage: build
  script:
    - ./gradlew clean build -x test --stacktrace
  tags:
    - android
  only:
    - master
    - develop

Publish To GPlay:
  stage: publish
  script:
    - export USE_DEV=""
    - ./gradlew :app:publishApkProdRelease --stacktrace
  only:
      - master
  when: manual
  tags:
    - android

Publish Dev:
  stage: publish
  script:
    - ./gradlew assembleDevRelease
    - cd app/build/outputs/apk/dev/release
    - gsutil cp app-dev-release.apk gs://dev-apk
  only:
      - develop
  when: manual
  tags:
    - android

Push to Github:
  stage: source
  script:
    - git remote add github git@github.com:nyris/everybag.Express.Android.git
    - git push github master
  tags:
    - android
  when: manual
  only:
    - master